server:
  port: 18762                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: peer2         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:18761/eureka/
  server:
    enable-self-preservation: false   #去掉保护模式
    
spring:
  application:
    name: server