server:
  port: 8010
spring:
  application:
    name: wanghao-microservice-consumer-movie-ribbon
eureka:
  client:
    service-url: 
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true